/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// EvictionRequestStatusApplyConfiguration represents a declarative configuration of the EvictionRequestStatus type for use
// with apply.
//
// EvictionRequestStatus represents the last observed status of the eviction request.
type EvictionRequestStatusApplyConfiguration struct {
	// conditions contain information about the eviction request.
	//
	// Eviction request specific conditions are: Evicted or Canceled (managed by Kubernetes),
	//
	// - Failed means that the eviction request is no longer being processed
	// by any eviction interceptor. This can happen if the request is canceled or if no interceptor
	// managee to evict the target (e.g. terminate or delete a pod).
	// - Evicted means that the target has been evicted (e.g. a pod has been terminated or deleted).
	//
	// The maximum length of the conditions list is 1000.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// observedGeneration is EvictionRequest's .metadata.generation observed by the eviction request controller.
	// The observed generation value cannot be negative and can only be incremented.
	// This field is managed by Kubernetes.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// targetInterceptors reference interceptors that should eventually respond to this eviction
	// request to help with the graceful eviction of a target. These interceptors are selected
	// sequentially, in the order in which they appear in the list and are added to the
	// .status.activeInterceptors in a rolling fashion.
	//
	// If the target is a pod, the field is populated from Pod's .spec.evictionInterceptors. Default
	// interceptors may be added to the list according to the target.
	//
	// Default interceptors:
	// - imperative-eviction.k8s.io interceptor is appended to the end of the list if the target is
	// a pod. It will call the /evict API endpoint. This call may not succeed due to
	// PodDisruptionBudgets, which may block the pod termination. It will update the interceptor
	// message and try again with a backoff.
	//
	// The maximum length of the interceptors list is 16.
	// This field is immutable once set.
	// This field is managed by Kubernetes.
	TargetInterceptors []TargetInterceptorApplyConfiguration `json:"targetInterceptors,omitempty"`
	// activeInterceptors store a list of interceptors that should currently interact with the
	// eviction process by updating .status.interceptors[], where .name is the active interceptor
	// name. InterceptorStatus fields should be periodically updated to indicate the progress or
	// completion of the eviction process. If .status.interceptors[].heartbeatTime field is not
	// updated within 20 minutes, the eviction request is passed over to the next interceptor.
	//
	// The maximum allowed number of active interceptors is 1. An active interceptor is removed from
	// this list when .status.interceptors[].completionTime is set.
	// This field is managed by Kubernetes.
	ActiveInterceptors []string `json:"activeInterceptors,omitempty"`
	// processedInterceptors store a list of interceptors that have previously been selected
	// and added to ActiveInterceptors. These interceptors may have reached completion, been
	// canceled, failed to start or failed to update .interceptors[].heartbeatTime` in a timely
	// manner.
	// Please refer to the InterceptorStatus for each interceptor for more details.
	// This field is managed by Kubernetes.
	ProcessedInterceptors []string `json:"processedInterceptors,omitempty"`
	// interceptors represents the eviction process status of each declared interceptor. Only
	// ActiveInterceptors should update the interceptor statuses.
	//
	// The interceptor list should be the same length and have the same .name fields as
	// .status.targetInterceptors. Only interceptors with .name that are included in
	// .status.activeInterceptors can be mutated. First initialization of the list is allowed.
	//
	// Each InterceptorStatus is managed by the designated interceptor.
	Interceptors []InterceptorStatusApplyConfiguration `json:"interceptors,omitempty"`
}

// EvictionRequestStatusApplyConfiguration constructs a declarative configuration of the EvictionRequestStatus type for use with
// apply.
func EvictionRequestStatus() *EvictionRequestStatusApplyConfiguration {
	return &EvictionRequestStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *EvictionRequestStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *EvictionRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *EvictionRequestStatusApplyConfiguration) WithObservedGeneration(value int64) *EvictionRequestStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithTargetInterceptors adds the given value to the TargetInterceptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetInterceptors field.
func (b *EvictionRequestStatusApplyConfiguration) WithTargetInterceptors(values ...*TargetInterceptorApplyConfiguration) *EvictionRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargetInterceptors")
		}
		b.TargetInterceptors = append(b.TargetInterceptors, *values[i])
	}
	return b
}

// WithActiveInterceptors adds the given value to the ActiveInterceptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveInterceptors field.
func (b *EvictionRequestStatusApplyConfiguration) WithActiveInterceptors(values ...string) *EvictionRequestStatusApplyConfiguration {
	for i := range values {
		b.ActiveInterceptors = append(b.ActiveInterceptors, values[i])
	}
	return b
}

// WithProcessedInterceptors adds the given value to the ProcessedInterceptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProcessedInterceptors field.
func (b *EvictionRequestStatusApplyConfiguration) WithProcessedInterceptors(values ...string) *EvictionRequestStatusApplyConfiguration {
	for i := range values {
		b.ProcessedInterceptors = append(b.ProcessedInterceptors, values[i])
	}
	return b
}

// WithInterceptors adds the given value to the Interceptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Interceptors field.
func (b *EvictionRequestStatusApplyConfiguration) WithInterceptors(values ...*InterceptorStatusApplyConfiguration) *EvictionRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInterceptors")
		}
		b.Interceptors = append(b.Interceptors, *values[i])
	}
	return b
}
